### ISSUE TITLE
Add Docker support to Blaezi.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/blaezi#1]
**What needs to be done:**
Add a Dockerfile to the project which would build and run blaezi.

**Prerequisites:**
- Set up Blaezi on your local environment.
- Test with the [example](https://github.com/burntcarrot/blaezi#tests) on a server.
- Basic Docker knowledge.

**Comment by burntcarrot** [comment]
**This issue is also open for Hacktoberfest 2021. Feel free to contribute!**

**Comment by DGKSK8LIFE** [comment]
Please assign me to this issue!

**Comment by burntcarrot** [comment]
Good luck with the PR! 😄 @DGKSK8LIFE

**Comment by burntcarrot** [comment]
@DGKSK8LIFE Since you have 3 issues assigned to you already, I think it is fair to let someone else to work on this issue. I hope you would understand. 😄

Since we have a PR ready here, I hope you can work on other issues assigned to you. Thanks for your time! ☺

**Comment by irvv17** [comment]
> @DGKSK8LIFE Since you have 3 issues assigned to you already, I think it is fair to let someone else to work on this issue. I hope you would understand. 😄
> 
> Since we have a PR ready here, I hope you can work on other issues assigned to you. Thanks for your time! ☺

Sorry about this I've started to work on this issue and I didn't comment here, sorry and Thank you, guys.
