### ISSUE TITLE
Add Docker Hub support.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/blaezi#3]
The proposed workflow:
- Create a Github Action for publishing images to Docker Hub on push to main (latest tag)
- Use the same action for publishing tagged images (for example, `v0.1`, etc.) to Docker Hub while creating Github releases.

cc: @irvv17

**Comment by marce1994** [comment]
Can I take this one?

**Comment by burntcarrot** [comment]
If you think you're comfortable with Go and Docker, I'd suggest you to take this up.

**Comment by marce1994** [comment]
I don't know with go, but I'm comfortable with docker and GitHub actions.

**Comment by burntcarrot** [comment]
Yes, then you can go ahead, there is a Dockerfile in the repo for references.

Waiting for your PR! ☺

**Comment by marce1994** [comment]
https://hub.docker.com/r/marce1994/blaezi/tags?page=1&ordering=last_updated I think it worked

**Comment by burntcarrot** [comment]
Resolved via #4.
