### ISSUE TITLE
Add GoReleaser support.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/blaezi#5]
We can use [GoReleaser](https://goreleaser.com) for automating releases with Github Actions.

Here is a [tutorial](https://goreleaser.com/ci/actions/) on how to use [GoReleaser](https://goreleaser.com) with Github Actions.

The action should only run on tags, and not on every push and PR.

**Comment by krishnaindani** [comment]
can I work on this?

**Comment by burntcarrot** [comment]
Feel free to work on this, I've assigned it to you :)

**Comment by krishnaindani** [comment]
Thank you

**Comment by krishnaindani** [comment]
Let me know what do you think of this https://github.com/burntcarrot/blaezi/pull/8

**Comment by burntcarrot** [comment]
Resolved via #8.
