### ISSUE TITLE
Make number of goroutines configurable.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/blaezi#7]
We could make the number of goroutines configurable while sending workers to perform tests:

https://github.com/burntcarrot/blaezi/blob/6d0add41852928a64474170214b5b9409c0bc622/inspector.go#L104-L108

**Comment by krishnaindani** [comment]
Thank you

**Comment by krishnaindani** [comment]
Do you have any specific approach in mind? I was thinking to add a goroutines field to this struct https://github.com/burntcarrot/blaezi/blob/6d0add41852928a64474170214b5b9409c0bc622/inspector.go#L26 and update the function definition here https://github.com/burntcarrot/blaezi/blob/6d0add41852928a64474170214b5b9409c0bc622/inspector.go#L32. 

The input will be take as flag while we run the program. What do you think?

**Comment by krishnaindani** [comment]
yes thats the plan. I will create a pr for it.

**Comment by krishnaindani** [comment]
Let me know if anything needs to be updated. I have added the PR https://github.com/burntcarrot/blaezi/pull/9

**Comment by burntcarrot** [comment]
Resolved via #9.
